export default {
    killerMove(state,move){
        state.killerTime=move
        console.log(state)
    },
    gameSetCard(state,option){
        state[option.cardType]=option.cardName
    },
    deepReset(state){
        state.meanCard=''
        state.clueCard=''
    },
    witnessMove(state){
        state.witnessTime=true
    },
    gameProgress(state,add){
        state.progress+=add
    },
    setSceneCard(state,card){
        state.SceneCards.push(card)
        console.log(state.SceneCards)
    },
    gameResetSceneCard(state){
        state.SceneCards=[]
    }
}
